# Generated by Django 4.1.2 on 2022-10-07 23:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=250)),
                ('device_type', models.CharField(max_length=250)),
                ('browser_type', models.CharField(max_length=250)),
                ('browser_version', models.CharField(max_length=250)),
                ('os_type', models.CharField(max_length=250)),
                ('os_version', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('was_downloaded', models.BooleanField(default=False)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.userdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Downloaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('downloade_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.userdevice')),
            ],
        ),
    ]
